name: quatriemeWorkflow.yml
on:
  push:
  workflow_dispatch:
jobs:
  showinfo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: lsla
        run: ls -la
      - name: tentative build
        run: make build
