name: troisiemeWorkflow.yml
on:
  push:
  workflow_dispatch:
jobs:
  showinfo:
    runs-on: ubuntu-latest
    container:
      image: alpine:3.22
    steps:

      - name: information sur le stockage
        run: lsblk

      - name: information sur le noyau utilis√©
        run: uname -a
